[package]
name = "s1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hoge"
path = "src/hoge.rs"


[dependencies]
