services:
  node1:
    stop_grace_period: 0s
    build:
      context: ../client
      dockerfile: ContainerFile
    networks:
      testnet:
        ipv4_address: 192.168.10.100
    command: sh -c "sleep 1; ping -c 1 node2;  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR root@node2 ls .ssh"

  node2:
    stop_grace_period: 0s
    build:
      context: ../server
      dockerfile: ContainerFile
    networks:
      testnet:
        ipv4_address: 192.168.10.101

networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
