FROM ubuntu:22.04 as redirect

COPY src/redirect.c /redirect.c

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
       gcc \
 && apt-get clean \
 && gcc -shared -fPIC /redirect.c -o /redirect.so -ldl

#-----------------------------------------------------

FROM ubuntu:22.04


COPY --from=redirect /redirect.so /redirect.so

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
       net-tools openssh-client netcat \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*


ENV LD_PRELOAD=/redirect.so
